# Generated by Django 2.2.5 on 2019-09-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='nome_misculas_sem_espaco',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
