# Generated by Django 2.2.5 on 2019-09-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperatura', '0002_cidade_nome_misculas_sem_espaco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='nome_misculas_sem_espaco',
        ),
    ]
