# Generated by Django 2.2.5 on 2019-09-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatura', '0003_remove_cidade_nome_misculas_sem_espaco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperatura',
            name='data_e_hora',
        ),
        migrations.AddField(
            model_name='temperatura',
            name='data',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatura',
            name='hora',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='valor',
            field=models.CharField(max_length=2),
        ),
    ]
