# Generated by Django 2.2.5 on 2019-09-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatura', '0004_auto_20190917_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='woeid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
