# Generated by Django 2.2.5 on 2019-09-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatura', '0005_cidade_woeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='woeid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
