# Generated by Django 2.2.5 on 2019-09-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatura', '0008_auto_20190917_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='custom_city',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
