# Generated by Django 2.2.5 on 2019-09-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperatura', '0009_cidade_custom_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=2)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cidade',
            new_name='City',
        ),
        migrations.DeleteModel(
            name='Temperatura',
        ),
        migrations.AddField(
            model_name='temperature',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='temperatura.City'),
        ),
    ]
